# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
baseurl:
# It will redirect your site to this url
url                 : https://blog.jiyunkeji.net
title               : 极云科技
name                : 极云科技
subtitle            : "极云科技知识分享"
description         : "极云科技知识分享"
repository          : lansecong/999_KaiFaBuBlogs_01.001
keywords            : 极云科技, 天津极云科技有限公司, 极云科技开发部, 极云, 极云科技分享社区 ,极云科技知识分享
date_format         : "ordinal"
timezone            : Asia/Shanghai
encoding            : "utf-8"
side_bar_repo_limit : 3

author              : lansecong
github_username     : lansecong
location            : TianJin, China
email               : zhsc@kingdee-cloud.cn

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate            : 12
lsi                 : true
quiet               : false
future              : true
excerpt_separator   : "\n\n"                # 摘录的分隔符
permalink           : /:year/:month/:day/:title    # 博文发布的 URL，伪静态
plugins:
  - jekyll-github-metadata                  # github 元信息
  - rouge
  - jekyll-octicons                         # 支持 octions 图标
  - jekyll-paginate                         # 分页
  - jekyll-feed                             # 自动生成 SSR 源
  - jemoji                                  # 解析 emoji
  - jekyll-sitemap                          # 自动生成 sitemap
  - jekyll-seo-tag                          # 自动 SEO 头信息生成
#   - jekyll-html-pipeline                  #
#   - jekyll-mentions                       # 用于 @github 用户
collections:
  wiki:
    output          : true
    permalink       : /wiki/:path.html
  design-mode: 
    output          : true
    permalink       : /design-mode/:path.html



# 导航
navs:
  -
    href            : /
    label           : 首页

  -
    href            : /categories/
    label           : 分类

  -
    href            : /archives/
    label           : 归档

  # -
  #   href            : /wiki/
  #   label           : 维基

  -
    href            : /links/
    label           : 链接

  -
    href            : /about/
    label           : 关于

subscribe_rss       : /feed.xml

# 评论模块
# gitalk:
#   owner             : 
#   repo              : 
#   clientID          : 
#   clientSecret      : 

# 站内搜索
simple_jekyll_search:
  fulltext          : true

# leanCloud 访问统计
# leancloud:
#   enable: true
#   app_id: 7EiyLoiTRMpJGKx5Jyy6FV0S-gzGzoHsz
#   app_key: 0l02blBLDj6noCkLMoF76LD8
#   data_class_name: visited_times
#   ip_class_name: visiting_ip

# 谷歌分析
# google:
#   analytics_id      : UA-146513129-1

# 备案号
beian               : 津ICP备14007082号 
MIIT                : http://www.beian.miit.gov.cn